### ISSUE TITLE
Error thrown while opening WSC dialog

### ISSUE THREAD

**Issue by Tade0** [WebSpellChecker/ckeditor-plugin-wsc#33] opened 2015-11-19 09:35 UTC
Bug in CKEditor: http://dev.ckeditor.com/ticket/13947
### Steps to reproduce
1. Open CKEditor (hash: `b34ea4de6106ce5513da723ba42c3ba52da7424a`) with WSC plugin (hash: d25e33615e)
2. Click "Check spelling".
### Expected result

Dialog is created, no errors.
### Actual result

Sometimes there's an `Object doesn't support property or method 'isVisible'` error thrown in the console.

Error is thrown in this line:
https://github.com/ckeditor/ckeditor-dev/blob/d277ad1230d5e269a309ece0723eebcd5efd8282/plugins/dialogui/plugin.js#L934
### Other details (browser, OS, CKEditor version, installed plugins)

IE11, Win 8.1, CKEditor 4.5.5

**Comment by WebSpellChecker** [comment] 2016-03-29 17:37
Can't reproduce. Could you please describe more clear steps.

**Comment by artiq5** [comment] 2016-09-14 16:49
@Tade0 any updates on this?

**Comment by f1ames** [comment] 2017-04-20 12:54
I think I am able to provide more specific steps to reproduce the issue:

1. Open the editor with `WSC` plugin.
1. Set content to `<p>an instance of ...</p>`.
1. Open `WSC` dialog and go to `Thesaurus` tab.
1. Replace _instance_ with some other word.
1. Close dialog by clicking `Finish Checking`.
1. Open `WSC` dialog.

Error is thrown:
![image](https://cloud.githubusercontent.com/assets/1061942/25231690/12ef8ba8-25d9-11e7-9901-b5f10d9d8776.png)

Tested with CKEditor https://github.com/ckeditor/ckeditor-dev/commit/2e815d09bc9ffc790088f0b44a59a5b27a395e1b and WSC 4.8.7.0.

**Comment by wsc-bug-hunter** [comment] 2017-04-21 09:59
Dear @f1ames ,

We tried to reproduce issue with your steps but without any success.
We would like to find out the root cause of this issue. That's why we need your help:
1. Could you please specify if there are any other editors on the page except CKEditor?
2. Could you please provide the html code of the page or give us an access to the test environment where this issue can be reproduced?

Thank you and sorry for any inconveniences. 

We are looking forward to your reply.
Regards,
The WebSpellChecker QA Team

**Comment by f1ames** [comment] 2017-04-21 11:24
Thank you for validating the issue, the exact steps on my side to reproduce the issue:

1. Clone the latest `ckeditor-dev/major` (https://github.com/ckeditor/ckeditor-dev/commit/191a21f377b500d661acd7b7c0f8508b111b83aa).
1. Go to `./ckeditor-dev/plugins/` and clone `WSC` there (https://github.com/WebSpellChecker/ckeditor-plugin-wsc/commit/edc4af56f4602dd98be04c7a730a3b8ec3d3b97a) as `./wsc`.
1. Open `./ckeditor-dev/config.js` and add `wsc` to `config.plugins` so the plugin will be included.
1. Open `./ckeditor-dev/samples/index.html` in a browser (I used Chrome 57.0.2987.133 (64-bit) on OSX).
1. Switch to `Source mode` in CKEditor.
1. Replace whole content with `<p>an instance of ...</p>`.
1. Switch back to `WYSIWYG` mode.
1. Open `WSC` dialog and go to `Thesaurus` tab.
1. Replace _instance_ with _ideal_ (using `Change to` button).
1. Close dialog by clicking `Finish Checking`.
1. Open `WSC` dialog.

After the 11th step, error mentioned in my previous comment is thrown.

**Comment by wsc-bug-hunter** [comment] 2017-04-21 16:02
Dear @f1ames ,

Thank you so much for such detailed steps. We were able to reproduce the issue.  The problem comes out when we use the Source mode in the CKEditor. 

I have created a task for our Dev Team and notified them.

Thank you so much for your help!
Sincerely,
The WebSpellChecker QA Team

**Comment by f1ames** [comment] 2017-04-24 06:10
@wsc-bug-hunter, I am glad it was helpful and made possible to reproduce the issue. If any more information is needed I am here to help.
Waiting for the update on the issue.

**Comment by wsc-bug-hunter** [comment] 2017-04-27 11:22
Dear @f1ames,
We are glad to inform you that issue with the console error has been fixed and will be released  in the middle of May with the product version 4.8.9.

Thank you so much for your patience and your help.

Sincerely,
The WebSpellChecker QA Team

**Comment by f1ames** [comment] 2017-04-27 11:25
Thank you for the quick fix!

**Closed** 2017-08-19 11:16 UTC
Labels: question
