### ISSUE TITLE
WSC dialog throws error after resize

### ISSUE THREAD

**Issue by Comandeer** [WebSpellChecker/ckeditor-plugin-wsc#35] opened 2015-11-19 12:44 UTC
Bug in CKEditor: http://dev.ckeditor.com/ticket/13953
## Steps to reproduce
1. Open CKEditor (hash: `b34ea4de6106ce5513da723ba42c3ba52da7424a`) with Web Spell Checker (hash: d25e33615eb0a6c1a5f887621406108a59f2edbf).
2. Open console.
3. Click "Spell Checker" button and select "Check spelling" option.
4. Close the dialog.
5. Resize the browser's window to have < 400px.
6. Repeat step 3.
## Expected result

No error is thrown.
## Actual result

`Invalid argument.` is thrown. It's probably caused by [`if` on lines 3117-3121 of `dialogs/wsc.js`](https://github.com/WebSpellChecker/ckeditor-plugin-wsc/blob/d25e33615eb0a6c1a5f887621406108a59f2edbf/dialogs/wsc.js#L3117-L3121) .
## Other details (browser, OS, CKEditor version, installed plugins)

Internet Explorer 8 on Windows XP

**Comment by WebSpellChecker** [comment] 2015-12-21 13:50
The issue is confirmed and reported into our internal bugtracking system with low priority.

**Comment by WebSpellChecker** [comment] 2015-12-21 13:53
The issue is confirmed and reported into our internal bugtracking system with low priority.

**Comment by wsc-julia-shaptala** [comment] 2017-09-06 12:33
Hello!

This issue won't be fixed as we no longer support EI 8 browser. All the product functionality works properly in IE 8, but no further fixes or development is planned so far.

Sincerely,

**Closed by wsc-julia-shaptala** 2017-09-06 12:33 UTC
Labels: bug
